CREATE TABLE ROOMS
(
    id    IDENTITY NOT NULL PRIMARY KEY,
    seats BIGINT
);

CREATE TABLE MOVIES
(
    id      IDENTITY NOT NULL PRIMARY KEY,
    title   VARCHAR(50),
    room_id BIGINT,
    FOREIGN KEY (room_id) REFERENCES MOVIES (id)
);

CREATE TABLE MOVIES_SCREENING_TIMES
(
    movie_id       BIGINT,
    FOREIGN KEY (movie_id) REFERENCES MOVIES (id),
    screening_time TIMESTAMP
);


-- ALTER TABLE MOVIES
--     ADD FOREIGN KEY (room_id) REFERENCES ROOMS (id);

